/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Test OpenAPI with React
 * How cool is that
 * OpenAPI spec version: 0.1.0
 */

export type GetAllPizzas200PizzasItem = {
  id?: number;
  name?: string;
  price?: number;
};
