/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Test OpenAPI with React
 * How cool is that
 * OpenAPI spec version: 0.1.0
 */
import type { GetAllPizzas200PizzasItem } from './getAllPizzas200PizzasItem';

export type GetAllPizzas200 = {
  pizzas?: GetAllPizzas200PizzasItem[];
};
